#ifndef CONSTEXPR_JSON_ERROR_CODES_H
#define CONSTEXPR_JSON_ERROR_CODES_H

namespace cjson {
enum class ErrorCode {
  UNKNOWN,
  UNREACHABLE,
  NULL_READ_FAILED,
  BOOL_READ_FAILED,
  NUMBER_READ_FAILED,
  STRING_READ_FAILED,
  ARRAY_EXPECTED_COMMA,
  ARRAY_UNEXPECTED_TOKEN,
  OBJECT_EXPECTED_COLON,
  OBJECT_EXPECTED_COMMA,
  OBJECT_UNEXPECTED_TOKEN,
  OBJECT_KEY_READ_FAILED,
  TYPE_DEDUCTION_FAILED,
  TRAILING_CONTENT,
};
} // namespace cjson
#endif // CONSTEXPR_JSON_ERROR_CODES_H
